version: '3'
services:
  frontend:
    image: abhilash29/veggiemarket-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: abhilash29/veggiemarket-backend:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/veggiemarket
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

