name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  IMAGE_PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}/veggiemarket
  TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Frontend
        run: |
          docker build -t $IMAGE_PREFIX-frontend:$TAG -f website/Dockerfile website
          docker push $IMAGE_PREFIX-frontend:$TAG

      - name: Build Backend
        run: |
          docker build -t $IMAGE_PREFIX-backend:$TAG -f backend/Dockerfile backend
          docker push $IMAGE_PREFIX-backend:$TAG

